doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
        #'App\Users\Infrastructure\Doctrine\Migration': '%kernel.project_dir%/src/Users/Infrastructure/Doctrine/Migration'
        #'App\Projects\Infrastructure\Doctrine\Migration': '%kernel.project_dir%/src/Projects/Infrastructure/Doctrine/Migration'
        #'App\Issues\Infrastructure\Doctrine\Migration': '%kernel.project_dir%/src/Issues/Infrastructure/Doctrine/Migration'
