app_issues_add:
    path: /
    controller: App\Issues\Presentation\Api\Controller\AddIssueController
    methods:  [POST]

app_issues_resolve:
    path: /api/issues/{id}/resolve
    controller: App\Issues\Presentation\Api\Controller\ResolveIssueController
    methods:  [PATCH]

app_issues_unresolve:
    path: /api/issues/{id}/unresolve
    controller: App\Issues\Presentation\Api\Controller\UnresolveIssueController
    methods:  [PATCH]

app_issues_pin:
    path: /api/issues/{id}/pin
    controller: App\Issues\Presentation\Api\Controller\PinIssueController
    methods:  [PATCH]

app_issues_unpin:
    path: /api/issues/{id}/unpin
    controller: App\Issues\Presentation\Api\Controller\UnpinIssueController
    methods:  [PATCH]

app_issues_get_item:
    path: /api/issues/{id}
    controller: App\Issues\Presentation\Api\Controller\GetIssueController
    methods:  [GET]
