app_security_jwt_token:
    path: /api/jwt/token
    methods: [POST]

app_security_jwt_refresh:
    path: /api/jwt/refresh
    controller: App\Security\Presentation\Api\Controller\RefreshTokenController
    methods: [POST]
