# Users
users_register:
    path: /api/users
    controller: App\Users\Presentation\Api\Controller\RegisterUserController
    methods:  [POST]

users_edit:
    path: /api/users/{id}
    controller: App\Users\Presentation\Api\Controller\EditUserController
    methods:  [PATCH]

users_confirm:
    path: /api/users/{token}/confirm
    controller: App\Users\Presentation\Api\Controller\ConfirmUserController
    methods:  [PATCH]

users_disable:
    path: /api/users/{id}/disable
    controller: App\Users\Presentation\Api\Controller\DisableUserController
    methods:  [PATCH]

users_enable:
    path: /api/users/{id}/enable
    controller: App\Users\Presentation\Api\Controller\EnableUserController
    methods:  [PATCH]

# Projects
projects_create:
    path: /api/projects
    controller: App\Projects\Presentation\Api\Controller\CreateProjectController
    methods:  [POST]

projects_edit:
   path: /api/projects/{id}
   controller: App\Projects\Presentation\Api\Controller\EditProjectController
   methods:  [PATCH]

projects_archive:
    path: /api/projects/{id}/archive
    controller: App\Projects\Presentation\Api\Controller\ArchiveProjectController
    methods:  [PATCH]

projects_unarchive:
    path: /api/projects/{id}/unarchive
    controller: App\Projects\Presentation\Api\Controller\UnarchiveProjectController
    methods:  [PATCH]

projects_get_item:
    path: /api/projects/{id}
    controller: App\Projects\Presentation\Api\Controller\GetProjectController
    methods:  [GET]

projects_get_collection:
    path: /api/projects
    controller: App\Projects\Presentation\Api\Controller\GetProjectsController
    methods:  [GET]

# Issues
