parameters:
    app_jwt_private_key: '%kernel.project_dir%/%env(APP_JWT_PRIVATE_KEY)%'
    app_jwt_public_key: '%kernel.project_dir%/%env(APP_JWT_PUBLIC_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\Presentation\Api\Controller\AbstractController:
        abstract: true
        arguments:
            - '@Symfony\Component\Serializer\SerializerInterface'
            - '@App\Shared\Application\Bus\CommandBusInterface'

    App\:
        resource: '../src/*'
        exclude:
            - '../src/{Kernel.php}'
            - '../src/**/Application/Command/*Command.php'
            - '../src/**/Presentation/**/Action/*Action.php'
            - '../src/**/Exception/*'
            - '../migrations'

    App\Users\Presentation\Api\Controller\:
        resource: '../src/Users/Presentation/Api/Controller/*'
        tags: ['controller.service_arguments']

    App\Projects\Presentation\Api\Controller\:
        resource: '../src/Projects/Presentation/Api/Controller/*'
        tags: ['controller.service_arguments']

    App\Issues\Presentation\Api\Controller\:
        resource: '../src/Issues/Presentation/Api/Controller/*'
        tags: ['controller.service_arguments']

    App\Security\Presentation\Api\Controller\:
        resource: '../src/Security/Presentation/Api/Controller/*'
        tags: ['controller.service_arguments']

    App\Shared\Presentation\Backoffice\Controller\:
        resource: '../src/Shared/Presentation/Backoffice/Controller/*'
        tags: ['controller.service_arguments']

    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
            tags: [{ name: messenger.message_handler, bus: command.bus }]

        App\Shared\Application\Query\QueryHandlerInterface:
            tags: [{ name: messenger.message_handler, bus: query.bus }]

    App\Shared\Presentation\Api\Validation\InputParamConverter:
        tags:
            - { name: request.param_converter }
