parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude:
            - '../src/{Kernel.php}'
            - '../src/**/Application/Command/*Command.php'
            - '../src/**/Presentation/**/Action/*Action.php'
            - '../src/**/Exception/*'
            - '../migrations'

    App\Projects\Presentation\Api\Controller\:
        resource: '../src/Projects/Presentation/Api/Controller/*'
        tags: ['controller.service_arguments']

    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
            tags: [{ name: messenger.message_handler, bus: command.bus }]

    #App\Issues\Presentation\Api\Controller\:
    #    resource: '../src/Issues/Presentation/Api/Controller/*'
    #    tags: ['controller.service_arguments']

    App\Shared\Presentation\Http\Validation\ActionParamConverter:
        tags:
            - { name: request.param_converter }
