parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Shared\Presentation\Api\Controller\AbstractController:
        abstract: true
        arguments:
            - '@Symfony\Component\Serializer\SerializerInterface'
            - '@App\Shared\Application\Bus\CommandBusInterface'

    App\:
        resource: '../src/*'
        exclude:
            - '../src/{Kernel.php}'
            - '../src/**/Application/Command/*Command.php'
            - '../src/**/Presentation/**/Action/*Action.php'
            - '../src/**/Exception/*'
            - '../migrations'

    App\Users\Presentation\Api\Controller\:
        resource: '../src/Users/Presentation/Api/Controller/*'
        tags: ['controller.service_arguments']

    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
            tags: [{ name: messenger.message_handler, bus: command.bus }]

    App\Shared\Presentation\Api\Validation\InputParamConverter:
        tags:
            - { name: request.param_converter }
